name: note_plus
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  shimmer: ^3.0.0
  flutter_tabler_icons: ^1.43.0
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.8
  dio: ^5.9.0
  pin_code_fields: ^8.0.1
  flutter_dotenv: ^6.0.0
  logger: ^2.6.1
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  auto_route: ^10.1.2
  json_annotation: ^4.9.0
  flutter_quill: ^11.2.0
  flutter_quill_extensions: ^11.0.0
  delta_to_html: ^0.2.2
  flutter_quill_delta_from_html: ^1.4.2
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  
  generation:
    path: generation

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_i18n: ^0.36.2
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  json_serializable: ^6.6.1
  riverpod_lint: ^2.3.2
  auto_route_generator: ^10.1.0



flutter:
  uses-material-design: true
  assets:
    - env/
    - assets/locales/