name: generation
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  flutter_svg: ^2.2.0
  lottie: ^3.1.0
  equatable: ^2.0.5
  flutter_gen: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_gen:
  output: lib/src/asset/
  assets:
    outputs:
      package_parameter_enabled: true
  integrations:
    lottie: true
    flutter_svg: true


flutter:
  assets:
    - assets/lottie/
    - assets/icons/
    - assets/images/
    - assets/svg/
